version: '3.8'

services:
  frontend:
    image: peroxidemonke07/fantasy-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: peroxidemonke07/fantasy-backend:latest
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: "mongodb+srv://mayank:njr10psg@cluster0.vxdhx.mongodb.net/fantasy_app?retryWrites=true&w=majority&appName=Cluster0"  
      KEDRO_API_URL: "http://kedro-api:5008"
    depends_on:
      - kedro-api

  kedro-api:
    image: peroxidemonke07/fantasy-kedro-api:latest
    ports:
      - "5008:5008"
