apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mern-app
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: peroxidemonke07/fantasy-backend:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 5000
        env: 
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: mern-backend-secret
                key: mongo_url 
          
          - name: KEDRO_API_URL
            valueFrom:
              configMapKeyRef:
                name: backend-configmap
                key: KEDRO_API_URL
