apiVersion: v1
kind: Secret
metadata:
  name: mern-backend-secret
  namespace: mern-app
type: Opaque
data:
  mongo_url: bW9uZ29kYitzcnY6Ly9tYXlhbms6bmpyMTBwc2dAY2x1c3RlcjAudnhkaHgubW9uZ29kYi5uZXQvZmFudGFzeV9hcHA/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=